### ISSUE TITLE
Right sidebar of profile after sign up is funky

### ISSUE THREAD

**Issue by dummied** [tiy-indianapolis-ror-june2015/CalebTad-Week6Lab#41]
<img width="279" alt="screen shot 2015-08-09 at 10 12 42 pm" src="https://cloud.githubusercontent.com/assets/4174/9158373/e5d8660e-3ee3-11e5-8ea2-ae3e0062de6f.png">

**Comment by tsherlock86** [comment]
fixed with changing the user to squawk.user.avatar
