### ISSUE TITLE
Left side of profile after sign up is also funky

### ISSUE THREAD

**Issue by dummied** [tiy-indianapolis-ror-june2015/CalebTad-Week6Lab#42]
<img width="425" alt="screen shot 2015-08-09 at 10 13 56 pm" src="https://cloud.githubusercontent.com/assets/4174/9158378/fd5b9f6c-3ee3-11e5-8ace-ac6ef0b270f4.png">

**Comment by tsherlock86** [comment]
Added height and width to profile image.
