### ISSUE TITLE
Rather than check if a user is logged in as a nested if/else, use `authenticate_user!`

### ISSUE THREAD

**Issue by dummied** [tiy-indianapolis-ror-june2015/CalebTad-Week6Lab#49]
https://github.com/tiy-indianapolis-ror-june2015/CalebTad-Week6Lab/blob/master/app/controllers/profiles_controller.rb

You can simplify this a good bit.

Also, it might not be a bad idea to have a method on User that is something like `can_follow?(user)` to move some of the logic out of the controller and into a model.

For instance: Right now, can I follow a user even if I'm blocked?

**Comment by tsherlock86** [comment]
Added authenticate_user! and removed nested if/else
