### ISSUE TITLE
You're not using the rails_12factor gem

### ISSUE THREAD

**Issue by dummied** [tiy-indianapolis-ror-june2015/CalebTad-Week6Lab#52]
https://github.com/heroku/rails_12factor

Which is going to make those 500 errors a pain in the ass to hunt down.

Also, why is `bourbon` in there when we already have bootstrap?

**Comment by tsherlock86** [comment]
some things bootstrap wasn't allowing me to do. 

Removed bourbon.

Added rails_12factor
